GET http://localhost:3000/users/count

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "test2",
    "password": "12345"
}

###

GET http://localhost:3000/users?key=1234

###

GET http://localhost:3000/users?user=test2&password=12345&key=1234

###

GET http://localhost:3000/file