POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "test2",
    "password": "12345"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users?user=test2&password=12345